basePath: /
definitions:
  server.createRepoRequest:
    properties:
      description:
        type: string
      kind:
        type: string
      name:
        type: string
    type: object
  server.createRepoResponse:
    type: object
host: localhost:8080
info:
  contact:
    email: rhiad.ciccoli@gmail.com
    name: rhiadc
  description: This is the API for responsible for generating a microservice repository
    (based on the language chosen) with the infrastrucure repository as well
  termsOfService: http://swagger.io/terms/
  title: Infra provision orchestrator API
  version: "1.0"
paths:
  /create-repo:
    post:
      consumes:
      - application/json
      description: Returns a the link of the github project generated and the link
        of the infrastructure repository as well
      parameters:
      - description: Create New repo
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/server.createRepoRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/server.createRepoResponse'
        "400":
          description: Bad Request
          schema: {}
      summary: Create a repository for the type of service chosen
      tags:
      - workflow
schemes:
- http
- https
swagger: "2.0"
